[package]
name = "lillinput"
version = "0.1.1-alpha"
authors = ["Diego M. Rodríguez <diego@moreda.io>"]
edition = "2018"
description = "Connect libinput gestures to i3 and others"
repository = "https://github.com/diego-plan9/lillinput/"
license = "BSD-3-Clause"
keywords = ["i3", "touchpad", "x11", "libinput", "gestures"]
categories = ["command-line-utilities", "gui"]

[dependencies]
# Stick to clap 3.0.0-beta.2, as it requires rustc >= 1.54.0 and additional
# updates to `default_value_if` arguments.
clap = "=3.0.0-beta.2"
clap_derive = "=3.0.0-beta.2"
filedescriptor = "0.7.3"
i3ipc = "0.10.1"
input = "0.5.0"
itertools = "0.10.1"
libc = "0.2.101"
log = "0.4.14"
shlex = "1.1.0"
simplelog = "^0.10.0"
strum = { version = "0.21", features = ["derive"] }
strum_macros = "0.21"
