[package]
name = "lillinput"
version = "0.1.1-alpha"
authors = ["Diego M. Rodríguez <diego@moreda.io>"]
edition = "2018"
description = "Connect libinput gestures to i3 and others"
repository = "https://github.com/diego-plan9/lillinput/"
license = "BSD-3-Clause"
keywords = ["i3", "touchpad", "x11", "libinput", "gestures"]
categories = ["command-line-utilities", "gui"]

[dependencies]
clap = "3.0.0-beta.5"
clap_derive = "3.0.0-beta.5"
# Stick to filedescriptor 0.7.3, as 0.8.0+ require feature resolve.
filedescriptor = "0.7.3"
i3ipc = "0.10.1"
input = "0.7.0"
itertools = "0.10.1"
libc = "0.2.103"
log = "0.4.14"
shlex = "1.1.0"
simplelog = "0.10.2"
strum = { version = "0.21.0", features = ["derive"] }
strum_macros = "0.21.0"
