on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libudev-dev libinput-dev

      - name: cargo check
        uses: dtoolnay/rust-toolchain@stable
        run: cargo check

  test:
    needs: [fmt, lints]
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libudev-dev libinput-dev

      - name: cargo test
        uses: dtoolnay/rust-toolchain@stable
        run: cargo test

  fmt:
    needs: [check]
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtoolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  lints:
    needs: [check]
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtoolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install dependencies for clippy
        run: sudo apt-get update && sudo apt-get install libudev-dev libinput-dev

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings -W clippy::pedantic

      - name: Run cargo clippy (tests)
        run: cargo clippy --tests -- -D warnings -W clippy::pedantic
