on:
  push:
    tags:
    - 'lillinput/v[0-9]+.[0-9]+.[0-9]+*'

name: Cargo release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libudev-dev libinput-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish crate
        run: cargo publish --package lillinput --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
