on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

name: Cargo release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install libudev-dev libinput-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
